AWSTemplateFormatVersion: "2010-09-09"
Description: "S3 static website (minimal)"

Resources:
  # S3バケットを作成
  StaticSiteBucket:
    Type: AWS::S3::Bucket
    Properties:
      # 静的ウェブサイトホスティングの有効化
      WebsiteConfiguration:
        IndexDocument: index.html
        ErrorDocument: index.html
      # ここは“バケット側の” Public Access Block を個別にOFFにする
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true           # ACLは使わないのでtrueのままでOK
        IgnorePublicAcls: true
        BlockPublicPolicy: false        # ポリシー公開を許可
        RestrictPublicBuckets: false
        
  StaticSiteBucketPolicy:
    Type: AWS::S3::BucketPolicy
    Properties:
      Bucket: !Ref StaticSiteBucket
      PolicyDocument:
        Version: "2012-10-17"
        Statement:
          - Sid: PublicReadByPolicy
            Effect: Allow
            Principal: "*"
            Action: "s3:GetObject"
            Resource: !Sub "${StaticSiteBucket.Arn}/*"

Outputs:
  # デプロイ完了後に表示されるS3サイトのURL
  WebsiteURL:
    Value: !GetAtt StaticSiteBucket.WebsiteURL
    Description: "S3 static website endpoint"
