name: Build Backend

on:
  push:
    branches: [ develop, main ]
    paths:
      - "backend/**"
      - ".github/workflows/build-backend.yml"
  pull_request:
    branches: [ develop, main ]
    paths:
      - "backend/**"

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: backend
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"

      - name: Install deps
        run: npm ci

      - name: Build (tsc)
        run: npm run build

      - name: Upload artifact (dist)
        uses: actions/upload-artifact@v4
        with:
          name: backend-dist
          path: backend/dist
