name: Deploy static site to S3

on:
  push:
    branches: [ main ] # main ブランチに push されたら実行

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # ソースコードをチェックアウト
      - uses: actions/checkout@v4

      # AWS 認証情報をセットアップ（Secrets から読み込み）
      - uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      # CloudFormation を使って S3 バケットを作成/更新
      - name: Deploy CloudFormation (S3 bucket)
        run: |
          aws cloudformation deploy \
            --stack-name static-site-stack \               # スタック名
            --template-file infra/s3-site.yaml \           # 読み込むテンプレート
            --no-fail-on-empty-changeset                   # 変更がなくてもエラーにしない

      # frontend/ ディレクトリのファイルを S3 にアップロード
      - name: Upload site files (frontend/)
        run: |
          BUCKET_NAME=$(aws cloudformation describe-stack-resources \
            --stack-name static-site-stack \
            --query "StackResources[?LogicalResourceId=='StaticSiteBucket'].PhysicalResourceId" \
            --output text)

          aws s3 sync frontend/ s3://$BUCKET_NAME/ --delete
